# Generated by Django 4.1.3 on 2022-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_daily_rate_movie_genre_movie_number_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
