# Generated by Django 4.1.3 on 2022-11-23 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 4, 2, 2, 471844, tzinfo=datetime.timezone.utc)),
        ),
    ]
