name: .NET Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Azure Functions Core Tools
      shell: bash
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

    - name: Build
      run: dotnet build --no-restore 
    - name: Start containers 
      shell: bash
      run:  |
           export ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"
           echo ${ipaddr} > ipaddr.txt
           docker-compose  -f "DevOps/docker-compose.yml" up -d --build 
           sleep 60
           EMULATOR_HOST=${ipaddr}
           EMULATOR_PORT=8081
           EMULATOR_CERT_PATH=/tmp/cosmos_emulator.cert
           openssl s_client -connect ${EMULATOR_HOST}:${EMULATOR_PORT} </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $EMULATOR_CERT_PATH
           sudo cp $EMULATOR_CERT_PATH /usr/local/share/ca-certificates/cosmos_emulator.crt
           sudo update-ca-certificates


    - name: Start function apps
      shell: bash
      run: |
            rootDir=`pwd`
            ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"

            cd ./Services/HttpTriggerQueueOutput
            func host start --port 7071 &
            sleep 20

            cd ${rootDir}/Services/QueueTriggerCosmosOutput
            mv local.settings.json local.settings.json.original
            sed -e s/localhost/${ipaddr}/g local.settings.json.original > local.settings.json
            echo "*** local.settings.json after sed ***"
            cat local.settings.json
            func host start --port 7072 &
            sleep 20
            
            cd ${rootDir}/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
           
            cd ${rootDir}/Tests/QueueTriggerCosmosOutputTest
            mv appsettings.json appsettings.json.original
            sed -e s/localhost/${ipaddr}/g appsettings.json.original > appsettings.json
            echo '*** appsettings.json after sed ***'
            cat appsettings.json
            dotnet test . -c Debug

            cd ${rootDir}/Tests/HttpTriggerCosmosOutputTest
            mv appsettings.json appsettings.json.original
            sed -e s/localhost/${ipaddr}/g appsettings.json.original > appsettings.json
            echo '*** appsettings.json after sed ***'
            cat appsettings.json
            dotnet test . -c Debug
            
            cd ${rootDir}

