version: "3"
services:
  
  client:
   build:
      context: ./client
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: mean-v
   networks:
    -  mean-stack-net
   volumes:
    -  ./client/src:/usr/app/src
    -  ./client/public:/usr/app/public
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile.dev
   ports:
     - 5000:5000
   container_name: mean-backend
   networks:
     - mean-stack-net
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mean-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mean-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local