version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      WATCHPACK_POLLING: true 
      FAST_REFRESH: false
      CHOKIDAR_USEPOLLING: true
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://databaseMongo/vidly
      WATCHPACK_POLLING: true 
      FAST_REFRESH: false
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./backend:/app
    command: ./wait-for databaseMongo:27017 && npm run db:up && npm start
  databaseMongo:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:

