version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      WATCHPACK_POLLING: true 
      FAST_REFRESH: false
      CHOKIDAR_USEPOLLING: true
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://database_mongo/vidly
      WATCHPACK_POLLING: true 
      FAST_REFRESH: false
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
  database_mongo:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
